# Generated by Django 2.1.3 on 2018-12-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='information',
        ),
    ]
