# Generated by Django 2.1.2 on 2018-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialid', models.CharField(max_length=30, verbose_name='mpid')),
                ('prettyformula', models.CharField(max_length=30, verbose_name='化学式')),
                ('elements', models.CharField(max_length=30, verbose_name='元素')),
                ('structure', models.CharField(max_length=500, verbose_name='结构')),
                ('information', models.CharField(max_length=500, verbose_name='信息')),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
