# Generated by Django 2.1.2 on 2018-11-25 19:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bm_project', '0002_material'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='material',
            managers=[
                ('matobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
